language: node_js
node_js: "9"

stages:
  - precache # warm up cache for default Node.js version
  - lint # lint code and docs
  - test # all tests

before_install: |
  [[ ! -x ~/npm/node_modules/.bin/npm ]] && {
    cd ~/npm && npm install npm
    cd -
  } || true
  # avoids bugs around https://github.com/travis-ci/travis-ci/issues/5092
  export PATH=~/npm/node_modules/.bin:$PATH
install: npm ci --ignore-scripts
cache:
  directories:
    - ~/.npm # cache npm's cache
    - ~/npm # cache latest npm

jobs:
  include:
    - script: npm run coverage
    - script: npm run test-integration
    - script: npm run test-mocha

    - &node-mocha
      script: npm run test-mocha
      node_js: '8'

    - <<: *node-mocha
      node_js: '6'

    - &node-jest
      script: npm run test-jest
      node_js: '8'

    - <<: *node-jest
      node_js: '6'

    - stage: precache
      script: true

    - stage: lint
      script: npm run lint
